import { BriefcaseBusiness, FileText, Home, Scale, Sprout, Users } from "lucide-react";
import type { Lang } from "@/lib/i18n";
import { ProfessionalsSection } from "@/components/ProfessionalsSection";

export type PracticeAreaItem = { title: string; description: string; matters: string[] };
export type PracticeAreasData = { kicker: string; title: string; subtitle: string; items: PracticeAreaItem[] };

export const PRACTICE_AREAS_DEFAULTS: Record<Lang, PracticeAreasData> = {
  pt: { kicker: "Áreas de Atuação", title: "Áreas de atuação", subtitle: "Atendemos pessoas físicas e empresas em demandas consultivas, extrajudiciais e judiciais, com análise individualizada das particularidades de cada caso.", items: [
    { title: "Direito de Família e Sucessões", description: "Atuação jurídica em questões familiares e sucessórias, conduzida com conhecimento técnico, sensibilidade e atenção às particularidades de cada relação e patrimônio.", matters: ["Divórcios e dissolução de união estável", "Guarda e convivência", "Alimentos", "Reconhecimento de filiação", "Partilha de bens", "Inventários e arrolamentos", "Testamentos", "Planejamento sucessório", "Questões patrimoniais familiares"] },
    { title: "Direito Civil, Contratual e Imobiliário", description: "Assessoria jurídica em relações privadas, contratos e questões patrimoniais e imobiliárias, com atuação preventiva, extrajudicial e contenciosa.", matters: ["Elaboração e revisão de contratos", "Obrigações e relações contratuais", "Responsabilidade civil", "Locações", "Posse e propriedade", "Usucapião", "Regularização de imóveis", "Negociações e questões patrimoniais"] },
    { title: "Direito do Trabalho e Previdenciário", description: "Orientação e atuação em questões trabalhistas e previdenciárias, tanto na esfera consultiva quanto administrativa e judicial.", matters: ["Relações de trabalho", "Reclamações trabalhistas", "Verbas e direitos trabalhistas", "Orientação preventiva", "Benefícios previdenciários", "Aposentadorias", "Pensões e demais demandas perante o INSS"] },
    { title: "Direito Agrário e do Agronegócio", description: "Assessoria jurídica em relações agrárias e questões patrimoniais vinculadas à atividade rural, com atuação preventiva, contratual e contenciosa.", matters: ["Contratos agrários", "Arrendamento e parceria rural", "Questões possessórias e imobiliárias rurais", "Regularização de imóveis rurais", "Relações patrimoniais vinculadas à atividade rural", "Consultoria jurídica aplicada ao agronegócio"] },
    { title: "Consultas e Pareceres Jurídicos", description: "Atendimento jurídico para análise individualizada de situações e documentos, orientação sobre alternativas jurídicas e elaboração de pareceres quando a natureza da demanda assim exigir.", matters: ["Consulta jurídica", "Análise documental", "Orientação preventiva", "Avaliação de estratégias jurídicas", "Elaboração de pareceres"] },
  ]},
  es: { kicker: "Áreas de Actuación", title: "Áreas de actuación", subtitle: "Atendemos a personas y empresas en asuntos consultivos, extrajudiciales y judiciales, con análisis individualizado de las particularidades de cada caso.", items: [
    { title: "Derecho de Familia y Sucesiones", description: "Actuación jurídica en cuestiones familiares y sucesorias, conducida con conocimiento técnico, sensibilidad y atención a las particularidades de cada vínculo y patrimonio.", matters: ["Divorcios y disolución de unión estable", "Guarda y convivencia", "Alimentos", "Reconocimiento de filiación", "Partición de bienes", "Inventarios y sucesiones", "Testamentos", "Planificación sucesoria", "Cuestiones patrimoniales familiares"] },
    { title: "Derecho Civil, Contractual e Inmobiliario", description: "Asesoría jurídica en relaciones privadas, contratos y cuestiones patrimoniales e inmobiliarias, con actuación preventiva, extrajudicial y contenciosa.", matters: ["Elaboración y revisión de contratos", "Obligaciones y relaciones contractuales", "Responsabilidad civil", "Arrendamientos", "Posesión y propiedad", "Usucapión", "Regularización de inmuebles", "Negociaciones y cuestiones patrimoniales"] },
    { title: "Derecho Laboral y Previsional", description: "Orientación y actuación en cuestiones laborales y previsionales, tanto en la esfera consultiva como administrativa y judicial.", matters: ["Relaciones laborales", "Reclamaciones laborales", "Haberes y derechos laborales", "Orientación preventiva", "Beneficios previsionales", "Jubilaciones", "Pensiones y demás demandas ante el INSS"] },
    { title: "Derecho Agrario y Agronegocio", description: "Asesoría jurídica en relaciones agrarias y cuestiones patrimoniales vinculadas a la actividad rural, con actuación preventiva, contractual y contenciosa.", matters: ["Contratos agrarios", "Arrendamiento y asociación rural", "Cuestiones posesorias e inmobiliarias rurales", "Regularización de inmuebles rurales", "Relaciones patrimoniales vinculadas a la actividad rural", "Consultoría jurídica aplicada al agronegocio"] },
    { title: "Consultas y Dictámenes Jurídicos", description: "Atención jurídica para el análisis individualizado de situaciones y documentos, orientación sobre alternativas jurídicas y elaboración de dictámenes cuando la naturaleza del asunto así lo requiera.", matters: ["Consulta jurídica", "Análisis documental", "Orientación preventiva", "Evaluación de estrategias jurídicas", "Elaboración de dictámenes"] },
  ]},
};

const ICONS = [Users, Home, BriefcaseBusiness, Sprout, FileText];
export function PracticeAreasSection({ lang, data }: { lang: Lang; data?: Partial<PracticeAreasData> }) {
  const fallback = PRACTICE_AREAS_DEFAULTS[lang];
  const items = Array.isArray(data?.items) && data!.items!.length ? data!.items! : fallback.items;
  const content = { kicker: data?.kicker || fallback.kicker, title: data?.title || fallback.title, subtitle: data?.subtitle || fallback.subtitle, items };
  const featuredIndex = Math.max(0, items.findIndex(item => /fam[ií]lia|familia/i.test(item.title)));
  const featured = items[featuredIndex];
  const others = items.filter((_, i) => i !== featuredIndex);
  return <>
    <section id="planes" className="border-y border-border/60 bg-[#fbfaf7] py-20 sm:py-24 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-6">
      <div className="mx-auto max-w-3xl text-center"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-primary">{content.kicker}</p><h2 className="mt-3 font-display text-4xl tracking-[-0.035em] sm:text-5xl lg:text-6xl">{content.title}</h2><p className="mx-auto mt-5 max-w-2xl text-justify text-sm leading-6 text-muted-foreground sm:text-base">{content.subtitle}</p></div>
      <article className="mt-12 overflow-hidden rounded-[1.5rem] border border-primary/15 bg-primary text-primary-foreground shadow-[0_18px_45px_-26px_rgba(0,0,0,.45)]"><div className="grid md:grid-cols-[140px_1fr]"><div className="grid min-h-36 place-items-center border-b border-primary-foreground/15 md:border-b-0 md:border-r"><Scale className="size-14 text-[#d5b478]" strokeWidth={1.35}/></div><div className="p-6 sm:p-8"><h3 className="font-display text-2xl sm:text-3xl">{featured.title}</h3><p className="mt-2 max-w-4xl text-justify text-sm leading-6 text-primary-foreground/80">{featured.description}</p><div className="mt-5 border-t border-primary-foreground/20 pt-4"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#d5b478]">{lang === "pt" ? "Entre as matérias de atuação:" : "Entre las materias de actuación:"}</p><p className="mt-2 text-justify text-xs leading-5 text-primary-foreground/78 sm:text-sm">{featured.matters.join(" · ")}</p></div></div></div></article>
      <div className="mt-4 grid gap-4 md:grid-cols-2">{others.map((item,index)=>{const Icon=ICONS[(index+1)%ICONS.length];return <article key={`${item.title}-${index}`} className="rounded-[1.25rem] border border-border bg-background p-6 sm:p-7"><div className="grid gap-5 sm:grid-cols-[72px_1fr]"><div className="grid size-14 place-items-center rounded-full bg-[#f3ecdf] text-[#b08a52]"><Icon className="size-7" strokeWidth={1.45}/></div><div><h3 className="font-display text-xl leading-tight sm:text-2xl">{item.title}</h3><p className="mt-2 text-justify text-sm leading-6 text-muted-foreground">{item.description}</p><div className="mt-4 border-t border-border pt-3"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#a77e46]">{lang === "pt" ? "Entre as matérias de atuação:" : "Entre las materias de actuación:"}</p><p className="mt-2 text-justify text-xs leading-5 text-foreground/68">{item.matters.join(" · ")}</p></div></div></div></article>})}</div>
    </div></section>
    <ProfessionalsSection lang={lang} />
  </>;
}
